# Generated by Django 3.2.6 on 2021-08-05 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wall_profiles', '0001_initial'),
        ('wall_blogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(upload_to='posts/img/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(null=True)),
                ('creator', models.CharField(blank=True, max_length=200, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update', models.DateTimeField(auto_now=True)),
                ('user_owned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wall_profiles.profile')),
            ],
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
